### ISSUE TITLE
metaflow ui-service unknow bug

### ISSUE THREAD

**Issue by LennieGuy** [Netflix/metaflow-service#351] opened 2023-03-13 13:50 UTC
"id": "MetaflowS3Exception",
"traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/root/services/ui_backend_service/data/cache/client/cache_server.py\", line 307, in <module>\n    cli(auto_envvar_prefix='MFCACHE')\n  File \"/usr/local/lib/python3.7/site-packages/click/core.py\", line 1128, in __call__\n    return self.main(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/click/core.py\", line 1053, in main\n    rv = self.invoke(ctx)\n  File \"/usr/local/lib/python3.7/site-packages/click/core.py\", line 1395, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/usr/local/lib/python3.7/site-packages/click/core.py\", line 754, in invoke\n    return __callback(*args, **kwargs)\n  File \"/root/services/ui_backend_service/data/cache/client/cache_server.py\", line 301, in cli\n    Scheduler(store, max_actions).loop()\n  File \"/root/services/ui_backend_service/data/cache/client/cache_server.py\", line 199, in __init__\n    maxtasksperchild=512,  # Recycle each worker once 512 tasks have been completed\n  File \"/usr/local/lib/python3.7/multiprocessing/context.py\", line 119, in Pool\n    context=self.get_context())\n  File \"/usr/local/lib/python3.7/multiprocessing/pool.py\", line 176, in __init__\n    self._repopulate_pool()\n  File \"/usr/local/lib/python3.7/multiprocessing/pool.py\", line 241, in _repopulate_pool\n    w.start()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 112, in start\n    self._popen = self._Popen(self)\n  File \"/usr/local/lib/python3.7/multiprocessing/context.py\", line 277, in _Popen\n    return Popen(process_obj)\n  File \"/usr/local/lib/python3.7/multiprocessing/popen_fork.py\", line 20, in __init__\n    self._launch(process_obj)\n  File \"/usr/local/lib/python3.7/multiprocessing/popen_fork.py\", line 74, in _launch\n    code = process_obj._bootstrap()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.7/multiprocessing/process.py\", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.7/multiprocessing/pool.py\", line 121, in worker\n    result = (True, func(*args, **kwds))\n  File \"/root/services/ui_backend_service/data/cache/client/cache_worker.py\", line 29, in execute_action\n    execute(tempdir, action_cls, request)\n  File \"/root/services/ui_backend_service/data/cache/client/cache_worker.py\", line 56, in execute\n    invalidate_cache=req.get('invalidate_cache', False))\n  File \"/root/services/ui_backend_service/data/cache/get_log_file_action.py\", line 144, in execute\n    results = {**existing_keys}\n  File \"/usr/local/lib/python3.7/contextlib.py\", line 130, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/root/services/ui_backend_service/data/cache/utils.py\", line 130, in streamed_errors\n    get_traceback_str()\n  File \"/root/services/ui_backend_service/data/cache/utils.py\", line 124, in streamed_errors\n    yield\n  File \"/root/services/ui_backend_service/data/cache/get_log_file_action.py\", line 141, in execute\n    content = log_provider.get_log_content(task, logtype)\n  File \"/root/services/ui_backend_service/data/cache/get_log_file_action.py\", line 275, in get_log_content\n    return get_log_content(task, logtype)\n  File \"/root/services/ui_backend_service/data/cache/get_log_file_action.py\", line 197, in get_log_content\n    for datetime, line in task.loglines(stream)\n  File \"/root/services/ui_backend_service/data/cache/get_log_file_action.py\", line 196, in <listcomp>\n    (_datetime_to_epoch(datetime), line)\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/client/core.py\", line 1388, in loglines\n    ds_type, ds_root, stream, attempt, *self.path_components\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/client/filecache.py\", line 81, in get_logs_stream\n    return task_ds.load_logs(LOG_SOURCES, stream, attempt_override=attempt)\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/datastore/task_datastore.py\", line 45, in method\n    return f(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/datastore/task_datastore.py\", line 776, in load_logs\n    r = self._load_file(paths.keys(), add_attempt=False)\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/datastore/task_datastore.py\", line 924, in _load_file\n    for key, path, meta in load_results:\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/plugins/datastores/s3_storage.py\", line 139, in iter_results\n    r = s3.get(p, return_missing=True, return_info=True)\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/plugins/datatools/s3/s3.py\", line 897, in get\n    path, addl_info = self._one_boto_op(_download, url)\n  File \"/usr/local/lib/python3.7/site-packages/metaflow/plugins/datatools/s3/s3.py\", line 1315, in _one_boto_op\n    \"S3 operation failed.\\n\" \"Key requested: %s\\n\" \"Error: %s\" % (url, error)\n\nmetaflow.plugins.datatools.s3.s3.MetaflowS3Exception: S3 operation failed.\nKey requested: s3://dev-test/tzy/ParameterFlow/argo-avalon.user.tanzheyue.parameterflow-jmrxv/start/t-e051c938/0.runtime_stdout.log\nError: An error occurred () when calling the GetObject operation: \n",

As shown in the error report above, the ui can display artifacts and dags, but cannot load stdout and stderr. I have verified that the key is not identified correctly, and the code key is 0. runtime_ Stdout.log, but 0. task is actually generated_ stdout.log

**Comment by LennieGuy** [comment] 2023-03-13 13:50
@jfernandez need your help

**Comment by saikonen** [comment] 2023-03-15 09:30
Trying to reproduce this bug so thought of asking for some more details on your environment:

- what are the metaflow-ui versions (these can be seen under the "Quick links" in the UI)
- what was the version of the Metaflow library used for the flow? This might be visible as a system tag in the UI under Run details
-  are logs for other runs working through the UI, or are they throwing the same error?

are you able to access the logs directly through the client? If the logs are not enormous, you can try
```
namespace(None)
task = Task("pathspec_to_task")
task.stdout
```

**Comment by LennieGuy** [comment] 2023-03-15 12:11
Thank you for your reply. I have found a problem here. There is a problem with the error format of the S3 interface we use

**Comment by saikonen** [comment] 2023-07-03 12:55
closing this as possibly resolved (?). Feel free to reopen if it turns out to be caused by the Metaflow-service.

**Closed by saikonen** 2023-07-03 12:55 UTC
